# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnlyOffeceClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnlyOffeceClient
  pod 'Alamofire'
  pod 'Swinject'

  target 'OnlyOffeceClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnlyOffeceClientUITests' do
    # Pods for testing
  end

end
